package com.roy.coffeetrip.greendaolite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECTION".
 */
public class Collection {

    private Long id;
    private String Title;
    private String Url;
    private Integer ContentId;

    public Collection() {
    }

    public Collection(Long id) {
        this.id = id;
    }

    public Collection(Long id, String Title, String Url, Integer ContentId) {
        this.id = id;
        this.Title = Title;
        this.Url = Url;
        this.ContentId = ContentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getUrl() {
        return Url;
    }

    public void setUrl(String Url) {
        this.Url = Url;
    }

    public Integer getContentId() {
        return ContentId;
    }

    public void setContentId(Integer ContentId) {
        this.ContentId = ContentId;
    }

}
