package com.roy.coffeetrip.greendaolite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.roy.coffeetrip.greendaolite.Collection;
import com.roy.coffeetrip.greendaolite.UserName;

import com.roy.coffeetrip.greendaolite.CollectionDao;
import com.roy.coffeetrip.greendaolite.UserNameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDaoConfig;
    private final DaoConfig userNameDaoConfig;

    private final CollectionDao collectionDao;
    private final UserNameDao userNameDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        userNameDaoConfig = daoConfigMap.get(UserNameDao.class).clone();
        userNameDaoConfig.initIdentityScope(type);

        collectionDao = new CollectionDao(collectionDaoConfig, this);
        userNameDao = new UserNameDao(userNameDaoConfig, this);

        registerDao(Collection.class, collectionDao);
        registerDao(UserName.class, userNameDao);
    }
    
    public void clear() {
        collectionDaoConfig.getIdentityScope().clear();
        userNameDaoConfig.getIdentityScope().clear();
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

    public UserNameDao getUserNameDao() {
        return userNameDao;
    }

}
